2021-12-10 00:00:50,292 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-12-10 00:00:50,296 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /Users/ato/anaconda3/lib/python3.7/site-packages/instabot/bot/bot.py
2021-12-10 00:00:54,252 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-12-10 00:00:54,257 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /Users/ato/anaconda3/lib/python3.7/site-packages/instabot/bot/bot.py
2021-12-10 00:01:40,630 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-12-10 00:01:40,638 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /Users/ato/anaconda3/lib/python3.7/site-packages/instabot/bot/bot.py
2021-12-10 00:01:45,662 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-12-10 00:01:45,806 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2021-12-10 00:01:45,806 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2021-12-10 00:01:45,806 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2021-12-10 00:01:45,813 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
